### PR TITLE
Fix link for api-reference

### PR DESCRIPTION
**Pull request by guits**
Link is broken because of a typo () <=> []

Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

### CODE REVIEW

**Comment by rmohr** [comment]
Seems like this was also fixed by another PR which got already merged. Thanks. :+1:

**Comment by guits** [comment]
@rmohr not sure why you preferred to merge #90, a clone of #88 which was obviously opened first. Even if you simply missed my PR (out of 6 PRs...), you should at least be sorry for not noticing it.

Your attitude is not really encouraging people to contribute to the documentation.

My2cents

**Comment by rmohr** [comment]
Well I saw a bug report about this in another repo and pushed a fix. I did not see your PR and it was for sure no 'clone'. I am sorry if you felt that me saying 'thanks' with thumbs up was not friendly enough.

**Comment by fabiand** [comment]
*cough*

Heya - I think there was a misunderstanding. At least I have not seen any bad intent by anybody.

I thank you @guits for your contribution, please let this mishap not stop you.

**Pull request closed without merging**
