### PR TITLE
templates: examples: cnv.io -> kubevirt.io

### PR DESCRIPTION
**Pull request by fromanirh**
trivial rename for consistency

Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by rawagner** [comment]
@fromanirh thanks for heads up. I have created issue for web-ui to change the labels/annotations https://github.com/kubevirt/web-ui-components/issues/294

**Comment by fromanirh** [comment]
Any further comments? Maybe merge? (/cc @fabiand )

**Comment by fabiand** [comment]
wfm, thanks

**Pull request merged**
