### PR TITLE
Fix: fix path in architecture.md from absolute path to related

### PR DESCRIPTION
**Pull request by tjjh89017**
Image path is incorrect with starting slash
follow other page to fix it and remove the starting slash to be related path and be migratable again.

Signed-off-by: Date Huang <tjjh89017@hotmail.com>

### CODE REVIEW

**Comment by cydu-cloud** [comment]
> @mazzystr
> thanks a lot
> i rebase it to master branch
> 
> it seems pic's issue is fixed in #474
> but they changed it into abs path
> i think it's better to use related path because it can be still migrateable
> please check it

Sorry, didn't see your PR before. I created #479 to fix that with ralative path.

**Comment by mazzystr** [comment]
Ah ok.  I'll close then.

.....And welcome to KubeVirt.  We hope you'll stay awhile.  :)

**Comment by tjjh89017** [comment]
ok tks guys!

**Pull request closed without merging**
