### PR TITLE
Spelling fix in CDI documentation

### PR DESCRIPTION
**Pull request by t3hmrman**
missing an 'e'

### CODE REVIEW

**Comment by phoracek** [comment]
@t3hmrman thanks for the PR! Would you please re-push your changes with you signature? You can add the signature by calling `git commit --amend -s`.

**Comment by t3hmrman** [comment]
Hey @phoracek yeah no problem -- I tried to click the DCO guide and the link is broken, will do the amend within the hour.

**Review by phoracek — APPROVED** [review]
/lgtm

**Pull request merged**
