### PR TITLE
Adding the v1.1.0 release notes for Nov 7

### PR DESCRIPTION
**Pull request by aburdenthehand**
v1.1.0 release notes notes added to user guide based on those prepared for the release tag. 
Timestamp of release to be added once known.

### CODE REVIEW

**Comment by aburdenthehand** [comment]
@vladikr has review this with me and provided feedback that was immediately implemented.

**Comment by phoracek** [comment]
/lgtm
/approve

Feel free to cancel the hold once 1.1 is out

**Pull request merged**
