### PR TITLE
added quickstart guides to ToC

### PR DESCRIPTION
**Pull request by KiranSatyaRaj**
created a new file quickstarts.md and added the quickstart guides to user-guide
Fixes: #588 
Signed-off-by: KiranSatyaRaj <kiranjamy20021508@gmail.com>

### CODE REVIEW

**Comment by aburdenthehand** [comment]
/lgtm
Thanks @KiranSatyaRaj

**Comment by aburdenthehand** [comment]
@maiqueb - since you're familiar with this from #603, do you want to give it a quick check?

**Comment by KiranSatyaRaj** [comment]
> Thank you.
> 
> For the next time, you don't have to close the "old" PR and open a new one; you can force push to your fork w/ `--force` - i.e. `git push <your fork> <branch name> --force` - and it will overwrite the history of your fork, which in turn causes the opened PR to be updated.

Thank you so much for you time Miguel, I will keep this in mind.

**Review by aburdenthehand — APPROVED** [review]

**Comment by KiranSatyaRaj** [comment]
@cwilkers please go through this one as well, let me know if any more changes are required else merge the pull request

**Comment by cwilkers** [comment]
Hi @KiranSatyaRaj ,

Thanks for your work on this issue, the result flows much better.

/approve

**Pull request merged**
