### PR TITLE
Update debug.md

### PR DESCRIPTION
**Pull request by shubhamrajvanshi**

### CODE REVIEW

**Comment by shubhamrajvanshi** [comment]
@stu-gott @vladikr can one of you take a look

**Comment by cwilkers** [comment]
Thanks for the PR!

Next time, could you add some description about what the PR is for when you open it? I imagine this didn't get attention because you left the description blank.

/lgtm

**Comment by shubhamrajvanshi** [comment]
@cwilkers My bad I thought PR title was enough. Will keep in my mind next time.

**Pull request merged**
