### PR TITLE
owners, user-guide: set up owners from sigs

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:

Since we have the sigs formed for the several topics, let's establish ownership of the sections by each respective sig.

This PR adds and `OWNERS_ALIASES` file to capture the several aliases, copying from kubevirt/kubevirt. Also it adds `OWNERS` that refer to those sig groups, so that the groups can own the changes to the user-guide themselves.

Also it removes some users from the reviewers section who haven't shown
review activity for the last six months - this way we avoid assigning
them to the reviews and getting reviews stalled.

See https://kubevirt.devstats.cncf.io/d/46/pr-reviews-by-contributor?orgId=1&var-period=d7&var-repo_name=kubevirt%2Fuser-guide&var-reviewers=%22davidvossel%22&var-reviewers=%22rmohr%22&var-reviewers=%22stu-gott%22 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/cc @aburdenthehand @cwilkers @alicefr 

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jean-edouard** [comment]
@dhiller will we setup a job to open update PRs when OWNERS_ALIASES changes in kubevirt/kubevirt?

**Comment by dhiller** [comment]
> @dhiller will we setup a job to open update PRs when OWNERS_ALIASES changes in kubevirt/kubevirt?

Yeah, I think automation around this would make much sense - not yet sure what exactly we want to do around this. I'd say we store lists inside community repo and sync from there

**Review by jean-edouard — COMMENTED** [review]
/approve
/hold
Holding to give this some time to be seen

**Comment by alicefr** [comment]
/lgtm
Many thanks @dhiller for the quick PR!

**Comment by aburdenthehand** [comment]
/lgtm
Thanks for picking this up @dhiller

**Comment by dhiller** [comment]
/unhold

Noone has complained, so we seem to have reached silent consensus.

**Pull request merged**
