### PR TITLE
Document cluster memory overcommit

### PR DESCRIPTION
**Pull request by ahadas**
Document [#2304](https://github.com/kubevirt/kubevirt/pull/2304)

### CODE REVIEW

**Comment by fabiand** [comment]
@MarSik thoughts?

**Comment by MarSik** [comment]
The docs look good to me. The config option is just a simplification for users, right? Because you always could override the value in spec.resources. Also I wonder whether we are accounting for the qemu and guest overhead here. Because for normal cases (100%) the resources should not match the VM, but it should be VM + expected overhead (vgpu buffers, memory tables, ..).

**Comment by ahadas** [comment]
> The docs look good to me. The config option is just a simplification for users, right? Because you always could override the value in spec.resources. Also I wonder whether we are accounting for the qemu and guest overhead here. Because for normal cases (100%) the resources should not match the VM, but it should be VM + expected overhead (vgpu buffers, memory tables, ..).

Well, it simplifies things but the main benefit is that it replaces the ridiculously low default memory request of 8M with something that makes more sense. Users can still exlicitely specify everything if they wish, yes. And regarding the overhead, its overcommit is specified diffetently so no, it's not affected by this

**Comment by MarSik** [comment]
Then I would actually put itno the docs an explanation how this affects the actual memory request that will be used for the pod. It should be VM memory / overcommit + overhead, right?

**Comment by ahadas** [comment]
> Then I would actually put itno the docs an explanation how this affects the actual memory request that will be used for the pod. It should be VM memory / overcommit + overhead, right?

Right, unless [OvercommitGuestOverhead](https://github.com/kubevirt/kubevirt/pull/2416) is set.
I would rather prefer not documenting the existing configuration of the overhead as part of this PR, although it is indeed related, since this PR doesn't change it and in light of the [work-in-progress in that area](https://github.com/kubevirt/kubevirt/pull/2406).

**Comment by MarSik** [comment]
@ahadas Then just maybe add a line saying something like: The actual mempory request depends on additional configuration options like OvercommitGuestOverhead.

**Comment by ahadas** [comment]
> @ahadas Then just maybe add a line saying something like: The actual mempory request depends on additional configuration options like OvercommitGuestOverhead.

Done

**Pull request merged**
