### PR TITLE
Add user guide section for CPU features.

### PR DESCRIPTION
**Pull request by yanirq**
Added a new section for CPU features (flags).
This is based on https://github.com/kubevirt/kubevirt/pull/1978

### CODE REVIEW

**Comment by yanirq** [comment]
[[epic-node-compatibility-1.4] Support extra CPU flags (features) when starting a VM [initiative-vm-high-availability]](https://trello.com/c/FGD3RGsr/91-epic-node-compatibility-14-support-extra-cpu-flags-features-when-starting-a-vm-initiative-vm-high-availability)

**Comment by MarSik** [comment]
Please mention the relationship between the configured cpu features, libvirt (all passed in) and scheduler (some used in node selector when feature gate enabled).

**Comment by fabiand** [comment]
@vladikr can you please review?

**Pull request merged**
