### PR TITLE
Recommend OpenShift SR-IOV operator for deployment

### PR DESCRIPTION
**Pull request by booxter**

### CODE REVIEW

**Comment by booxter** [comment]
@fedepaol feel free to expand, though yes, my intention is to avoid details because things may change in the future in their repo and we probably don't want to update our docs every time it happens.

**Comment by fedepaol** [comment]
Your approach definitely sounds better, since it's immune to changes in the operator behaviour and I added the upstream specific bits in the operator's quickstart guide.

Let's keep it this way.

**Comment by booxter** [comment]
@slintes perhaps you could nudge it in merge queue. Thanks!

**Comment by booxter** [comment]
I'll take a risk and merge this myself. It has two approvals from networking team members, and it doesn't seem controversial, just lacks attention of usual suspects to merge patches. If it's not ok, let me know and I will refrain from doing it in the future.

**Comment by slintes** [comment]
> just lacks attention of usual suspects to merge patches

since you pinged me: I was on PTO

**Pull request merged**
