### PR TITLE
Add documentation for vnc proxy-only mode

### PR DESCRIPTION
**Pull request by vatsalparekh**
Signed-off-by: Vatsal Parekh <vparekh@redhat.com>

### CODE REVIEW

**Comment by codificat** [comment]
CI is not working at the moment on this repo

/assign @mazzystr 

who is working on a fix

**Comment by mazzystr** [comment]
We had a discussion re the pending content pull_reqs.  Repo owner will manually merge to avoid rework on the CI system.  I will rebase the pull/372.  

Hold label is removed @codificat

**Pull request merged**
