### PR TITLE
Moving codificat/hroyrh to emeritus_approvers...end of an era

### PR DESCRIPTION
**Pull request by mazzystr**
Signed-off-by: Chris Callegari <mazzystr@gmail.com>

### CODE REVIEW

**Review by davidvossel — COMMENTED** [review]
/approve

Thanks for all your help @codificat  @hroyrh

**Comment by mazzystr** [comment]
> /approve
> 
> Thanks for all your help @codificat @hroyrh

Gonna need you to tag lgtm also

**Comment by codificat** [comment]
/lgtm

It was great to contribute to the project! Keep on rocking!

**Pull request merged**
