### PR TITLE
Linked kubevirt labs to docs

### PR DESCRIPTION
**Pull request by KiranSatyaRaj**
Fixes: #587 
Signed-off-by: KiranSatyaRaj <kiranjamy20021508@gmail.com>

### CODE REVIEW

**Comment by jobbler** [comment]
Checked page and tested links.
/lgtm

**Comment by aburdenthehand** [comment]
/lgtm
@jobbler I don't have merge rights in this repo, are you right to merge?

**Review by aburdenthehand — APPROVED** [review]

**Pull request merged**
