### PR TITLE
NUMA.md add Additional Reading section

### LINKED ISSUE #755: update NUMA doco
It would be good to include mention of these NUMA related items on the [NUMA page](https://kubevirt.io/user-guide/virtual_machines/numa/):
-  Topology Manager: https://kubernetes.io/docs/tasks/administer-cluster/topology-manager/ on the NUMA page. It is required e.g. where SR-IOV network adaptor VF allocation needs to be aligned with cpu/memory. Here's an issue which provides some context: https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/issues/262
- Memory Manager: https://kubernetes.io/docs/tasks/administer-cluster/memory-manager/

### PR DESCRIPTION
**Pull request by ianb-mp**
**What this PR does / why we need it**:

Add 'Additional Reading' section to the NUMA page to mention related Kubernetes topics. 

**Which issue(s) this PR fixes** 

Fixes #755 

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fabiand** [comment]
@xpivarc @acardace is this something you can help with?

**Comment by porjo** [comment]
@phoracek @stu-gott please review

**Comment by acardace** [comment]
Not an expert in real-time and NUMA but looks good to me.

**Comment by fabiand** [comment]
/lgtm
/approve

according to Antonio's comment

**Comment by xpivarc** [comment]
+1

**Pull request merged**
