### PR TITLE
live-migration: no need of feature gates

### PR DESCRIPTION
**Pull request by victortoso**
Since v0.56, with the PR:
https://github.com/kubevirt/kubevirt/pull/8047

### CODE REVIEW

**Comment by aburdenthehand** [comment]
/lgtm
Although I do wonder, since v0.56 is now out of support, whether we just drop the whole para/section. 
Thanks @victortoso !

**Comment by victortoso** [comment]
Hi @aburdenthehand anything else missing for this?

**Comment by victortoso** [comment]
>  Although I do wonder, since v0.56 is now out of support, whether we just drop the whole para/section.

That's actually a good point. What lowest version we should keep in mind to update the user-guide?

**Comment by aburdenthehand** [comment]
@victortoso as you know we talked a bit about this in the community meeting. Since this is version is only recently out of support, it makes sense to cover it the way that you have.
I've created an issue (#701) to update our contributor guide to include this kind of information.

**Comment by vladikr** [comment]
Looks good to me. Thanks.
/approve

**Pull request merged**
