### PR TITLE
Fix doc for batchEviction{Size,Interval}

### PR DESCRIPTION
**Pull request by LittleFox94**
Documentation examples showed batchEvict{Size,Interval} instead of batchEviction{Size,Interval}.

### CODE REVIEW

**Comment by LittleFox94** [comment]
I changed the commit to include a `signed-off-by` line, but the bot does not seem to catch it and update the label - can you take a manual look at it, please? @fabiand @vladikr

**Comment by cwilkers** [comment]
/ok-to-test
Hopefully that will also update the DCO

**Comment by LittleFox94** [comment]
Hm the ok-to-test wasn't enough it seems, trying to retest, which should be allowed now at least

/retest

**Comment by cwilkers** [comment]
I have manually switched the labels for now, but will have to investigate if there's something wrong with our CI checks.

**Comment by cwilkers** [comment]
Was the change from "evict" to "eviction" related to a change in the API, or a typo in the original docs?
If the API changed, it would be helpful to link to that PR here (just in the conversation of this PR for future reference if needed.)

**Comment by LittleFox94** [comment]
This commit renamed from a completely different name to eviction: https://github.com/kubevirt/kubevirt/commit/f3f7819206fb152946a5239aea3c6021e3efc21f

While this added the docs, with evict: https://github.com/kubevirt/user-guide/commit/eb9664cb09b47a5ee6fc29709357bd494e2e7821

So I'd guess it's an oversight when writing the docs.

**Comment by cwilkers** [comment]
Thanks for the clarification, and the PR!
/approve
/lgtm

**Comment by LittleFox94** [comment]
Thanks for fighting with the CI @dhiller :)

**Comment by dhiller** [comment]
> Thanks for fighting with the CI @dhiller :)

You're welcome. In any case, if such a thing happens again, [here's the](https://prow.ci.kubevirt.io/plugins) list of plugins with some docs on how to use them.

**Pull request merged**
