### PR TITLE
netlify: break huge string

### PR DESCRIPTION
**Pull request by victortoso**
**What this PR does / why we need it**:
I was looking at the CI failure at https://github.com/kubevirt/user-guide/pull/751 and it complains about escaping, error is:

```
>   command = "source /opt/buildhome/python3.8/bin/activate; pip3 install mkdocs mkdocs-awesome-pages-plugin mkdocs-material; sed -i "s/site_url: https:\/\/kubevirt.io\/docs/site_url: https:\/\/kubevirt.io\//" /opt/build/repo/mkdocs.yml; sed -i "s/docs_dir: docs/docs_dir:/" /opt/build/repo/mkdocs.yml; echo "*** BEGIN /opt/build/repo/mkdocs.yml ***"; cat /opt/build/repo/mkdocs.yml; echo "*** END /opt/build/repo/mkdocs.yml ***"; mkdocs build -f /opt/build/repo/mkdocs.yml -d /opt/build/repo/site"
                                                                                                                                                          ^
```

Not easy to see the issue with a huge command line. This PR tries to break it down and fix the issue if any.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by victortoso** [comment]
Okay, now the logs are like:

 ```
Unknown escape character: 47 at row 6, col 28, pos 184:
5: pip3 install mkdocs mkdocs-awesome-pages-plugin mkdocs-material;
6> sed -i "s/site_url: https:\/\/kubevirt.io\/docs/site_url: https:\/\/kubevirt.io\//" /opt/build/repo/mkdocs.yml;
                              ^
7: sed -i "s/docs_dir: docs/docs_dir:/" /opt/build/repo/mkdocs.yml;
```

A clear improvement.

**Comment by aburdenthehand** [comment]
/lgtm
Nice one. Thanks @victortoso 
While we're at it, do we want to change the delimiter character in those sed commands to something that is not used in the string sub?
Maybe `|` ? WDYT?

**Comment by victortoso** [comment]
> Unknown escape character: 49 at row 6, col 50, pos 206:
> 6> sed -iE "s/(site_url: https:..kubevirt.io.)docs/\1/" /opt/build/repo/mkdocs.yml;
>                                                     ^

Even when trying to fix the usage of `\` I'm using `\`. :man_facepalming:

**Comment by jean-edouard** [comment]
/approve
Yes please! Thank you :)

**Comment by aburdenthehand** [comment]
/lgtm
Muuuch cleaner. Thanks Victor!

**Pull request merged**
