### PR TITLE
docs: update virtctl examples and flags

### PR DESCRIPTION
**Pull request by codingben**
**What this PR does / why we need it**:

Add more virtctl examples and flags, copied from "virtctl upload-image --help".

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
/lgtm

**Comment by codingben** [comment]
Hi @aburdenthehand, can you please review and if it's approve it?

**Comment by 0xFelix** [comment]
@aburdenthehand is out, can you PTAL @phoracek?

**Comment by codingben** [comment]
Thanks @0xFelix @phoracek :)

**Pull request merged**
