### PR TITLE
Document NVMe passthrough

### PR DESCRIPTION
**Pull request by alicefr**
Add documentation for NVMe passthrough and its limitations for KubeVirt

### CODE REVIEW

**Comment by mazzystr** [comment]
This section looks and I'm happy to tag.

Question before doing so tho.  What do you think about the ordering of the page as whole top to bottom?  Do you think we should refactor so that it feels less zig-zag?  For instance I see there is a "Starting Virtual machine" section stuck right ion the middle then we get back to configuring for NVMe.

**Comment by alicefr** [comment]
@mazzystr yes I see your point! The only thing is that I have an example of VMI with the NVMe and moving the section before `Starting a Virtual Machine` sounds a bit weird to me. Either I remove the VMI example or... I'm not sure :)

**Review by dhiller — APPROVED** [review]
Thanks!

**Comment by vladikr** [comment]
/lgtm
Thanks @alicefr !

**Comment by alicefr** [comment]
@mazzystr any further comments on this?

**Comment by mazzystr** [comment]
All good with me!  Thanks!

/lgtm
/approve

**Pull request merged**
