### PR TITLE
Fix broken links plus supporting fixes

### PR DESCRIPTION
**Pull request by mazzystr**
### 1) 063f3f82
* Rakefile, remove unnecessary target that carried over from website
* Config file....
  * site_url was incorrect and broke links on 404 page **<|** **THIS MIGHT BREAK STUFF.  LET'S TAKE A GOOD LOOK AT NETLIFY BEFORE DEPLOYING**
  * Add admonition to config (necessary for H1 txt in `web_console.md` and `templates.md`
* Fix broken links and selectors 
* Fix cosmetic whitespaces

```
$ make check_links

Makefile: Stop site
podman rm -f userguide 2> /dev/null; echo

Makefile: Check external and internal links

Building site...
mkdocs build -f mkdocs.yml -d site
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /srv/site
INFO    -  Documentation built in 0.84 seconds

Checks html files for broken external links (This can take a few mins to run) ...
Running ["LinkCheck", "ScriptCheck", "ImageCheck"] on ["./site"] on *.html...


Checking 186 external links...
Ran on 44 files!


HTML-Proofer finished successfully.

Checks html files for broken internal links (This can take a few mins to run) ...
Running ["LinkCheck", "ScriptCheck", "ImageCheck"] on ["./site"] on *.html...

Ran on 44 files!


HTML-Proofer finished successfully.
```

### 2) ea3d402
* As suspected having an empty `site_url` is the wrong thing to do per https://github.com/mkdocs/mkdocs/issues/2318
* `site_url` returned to original setting
* regex added to Rake file to remove `user-guide` uri from internal links.  `make check_links` completes sucessfully.
```
$ make check_links

Makefile: Stop site
podman rm -f userguide 2> /dev/null; echo

Makefile: Check external and internal links

Building site...
mkdocs build -f mkdocs.yml -d site
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /srv/site
INFO    -  Documentation built in 1.06 seconds

Checks html files for broken external links (This can take a few mins to run) ...
Running ["LinkCheck", "ScriptCheck", "ImageCheck"] on ["./site"] on *.html...


Checking 228 external links...
Ran on 44 files!


HTML-Proofer finished successfully.

Checks html files for broken internal links (This can take a few mins to run) ...
Running ["LinkCheck", "ScriptCheck", "ImageCheck"] on ["./site"] on *.html...


Ran on 44 files!


HTML-Proofer finished successfully.

```

### CODE REVIEW

**Comment by mazzystr** [comment]
@stu-gott Would you mind taking a look at this?

**Review by stu-gott — DISMISSED** [review]
/lgtm

**Comment by mazzystr** [comment]
@stu-gott rebase complete.  Would you mind tagging lgtm and approve?  Sorry that I need you right now.  I don't have my news guys geared up for maintainers yet.

**Review by stu-gott — APPROVED** [review]
/lgtm

**Pull request merged**
