### PR TITLE
Add information about cloud-init ConfigDrive

### PR DESCRIPTION
**Pull request by gonzolino**
This PR adds documentation for the features added in https://github.com/kubevirt/kubevirt/pull/2120

### CODE REVIEW

**Comment by mfranczy** [comment]
Looks good, thanks. Could you update disk and volumes section as well? I would add there cloud-init ConfigDrive under NoCloud. https://github.com/kubevirt/user-guide/blob/master/creating-virtual-machines/disks-and-volumes.adoc#cloudinitnocloud

**Comment by gonzolino** [comment]
Totally overlooked the disk and volumes section 😅 
Thanks for pointing it out. I added the section as you suggested.

**Comment by mfranczy** [comment]
@fabiand the feature has been merged, could you review this PR and merge if it looks good to you? I don't have RW permissions for this repo.

**Comment by fabiand** [comment]
Thanks for the contribution @gonzolino - and the help @mfranczy !

**Pull request merged**
