### PR TITLE
Live Migration: Add primary pod NIC name limitation

### PR DESCRIPTION
**Pull request by orelmisan**
**What this PR does / why we need it**:
Following https://github.com/kubevirt/kubevirt/pull/13018, it is possible to have a VM whose primary NIC is connected to a pod NIC with a name other than `eth0`.

In order for the migration to be successful, it is required for the both the source and target virt-launcher pods
to have the same primary NIC name, for example: `eth0`.

[1] https://github.com/kubevirt/community/pull/324

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by EdDev — APPROVED** [review]
Thanks!

This is correct with or without the support of having a primary pod interface name different from `eth0`.

**Comment by orelmisan** [comment]
[Change](https://github.com/kubevirt/user-guide/compare/1f0da3ac51cf4c1d1e78e9d991474c056c2161c1..2799407c8cc9db27cc750dd022266eadaedb1664): Updated commit message to be more accurate.

**Review by EdDev — APPROVED** [review]

**Comment by vladikr** [comment]
/approve
Thanks

**Pull request merged**
