### PR TITLE
Added Kubevirt v0.59.0 release notes

### LINKED ISSUE #657: Update Release Notes for v0.59.0
**Description:**

The release notes haven't been updated since v0.58.0 at https://kubevirt.io/user-guide/release_notes/ and there is a new release, https://github.com/kubevirt/kubevirt/releases/tag/v0.59.0 whose release notes needs to be updated in the user guides as well

### PR DESCRIPTION
**Pull request by adithyaakrishna**
**Description:**
This PR Fixes #657

### CODE REVIEW

**Comment by phoracek** [comment]
CC @aburdenthehand

**Comment by adithyaakrishna** [comment]
Had missed Kubevirt v0.58.1 release and have added it in the above commit :)

CC @phoracek @aburdenthehand

**Comment by aburdenthehand** [comment]
/lgtm
@adithyaakrishna Nice one - thanks a lot for putting this together!

**Comment by adithyaakrishna** [comment]
Lesssgooo 🎉

**Pull request merged**
