### PR TITLE
Update changelog

### PR DESCRIPTION
**Pull request by iranzo**
Update changelog

### CODE REVIEW

**Comment by iranzo** [comment]
Missing "/" ?

**Comment by rmohr** [comment]
> Missing "/" ?

Afaik this repo does not use lgtm and approve flows yet.

**Comment by iranzo** [comment]
Should then I wait for someone to merge it? do you want me to contrib tide merge flow?

**Comment by rmohr** [comment]
@iranzo I thought you would just merge.

**Comment by rmohr** [comment]
but great if you contribute tide.

**Pull request merged**
