### PR TITLE
Add Gemfile definition

### PR DESCRIPTION
**Pull request by iranzo**
Adds gemfile definition to ease setup by CI systems

### CODE REVIEW

**Comment by slintes** [comment]
sorry, I'm not familiar with this, can't provide a useful review :man_shrugging:

**Comment by iranzo** [comment]
> sorry, I'm not familiar with this, can't provide a useful review man_shrugging

Added you as we spoke about this...

In short, it adds the 'gem' that it's installed in `.travis.yml` in the standard way to deploy them.

Can you suggest someone to review this PR ?

Thanks!
Pablo

**Comment by booxter** [comment]
@fabiand @davidvossel @rmohr please take a look, this unbreaks CI for the `user-guide` repo. We can't pass gate for any other PRs until this merges. Thanks.

**Comment by iranzo** [comment]
Seems that also DCO was added later and status was not reported. I'm reuploading the patch to trigger it to recheck so that it can be merged

**Pull request merged**
