### PR TITLE
Fix manifest file name

### PR DESCRIPTION
**Pull request by nelsonspbr**
Current documentation to install CDI ([here](https://kubevirt.io/user-guide/#/installation/image-upload?id=install-cdi)) suggests deploying the `cdi-operator-cr.yaml` manifest. The correct file name should be `cdi-cr.yaml`, based on assets specified in https://github.com/kubevirt/containerized-data-importer/releases.

### CODE REVIEW

**Comment by nelsonspbr** [comment]
@codificat Thanks! It seems it is still waiting for your review, though.

**Review by codificat — APPROVED** [review]

**Review by stu-gott — APPROVED** [review]
/approve

**Comment by nelsonspbr** [comment]
@codificat I just fixed the signed-off issue. Could you please merge this one? Or am I missing anything from my side?

**Pull request merged**
