### PR TITLE
Rename registryDisk to containerDisk

### PR DESCRIPTION
**Pull request by petrkotas**
Rename the registryDisk to containerDisk.

Fixes: kubevirt/kubevirt#1308

---
This change is [Reviewable](https://reviewable.io/reviews/kubevirt/user-guide/155)

### CODE REVIEW

**Comment by slintes** [comment]
should we add a note here for some time that the name changed? @fabiand ?

**Comment by fabiand** [comment]
Yes please!

Very good point!

**Comment by petrkotas** [comment]
@slintes @fabiand updated the user-guide.

**Comment by fabiand** [comment]
Thanks!

**Pull request merged**
