### PR TITLE
Add KubeVirt Web UI to the installation section

### PR DESCRIPTION
**Pull request by mareklibra**

### CODE REVIEW

**Comment by mareklibra** [comment]
For consistency, I keep referring the OKD as OpenShift.
But this should be changed, I guess.

**Comment by jelkosz** [comment]
LGTM!

**Comment by fabiand** [comment]
@stu-gott can you please review?

**Comment by rmohr** [comment]
@mareklibra @jelkosz is the content here still correct?

**Comment by jelkosz** [comment]
@rmohr yes, still correct.

**Pull request merged**
