### PR TITLE
Add aburden as reviewer for user guide

### PR DESCRIPTION
**Pull request by aburdenthehand**
I would like to be more helpful with reviews for the user-guide.

To date I have helped review [16 PRs in this repo](https://github.com/kubevirt/user-guide/pulls?q=is%3Apr+reviewed-by%3Aaburdenthehand+is%3Aclosed+), and created [13 PRs that have been merged](https://github.com/kubevirt/user-guide/pulls?q=is%3Apr+author%3Aaburdenthehand+is%3Aclosed).

### CODE REVIEW

**Comment by jean-edouard** [comment]
Thank you @aburdenthehand for volunteering!
Might be a good idea to cc some/all approvers from https://github.com/kubevirt/user-guide/blob/main/OWNERS
/approve
/hold
Holding to give other approvers time to see this.

**Comment by aburdenthehand** [comment]
Thanks @jean-edouard 
/cc @vladikr @stu-gott @AlonaKaplan @phoracek @cwilkers 
(Don't want to ping everyone so every second approver :) )

**Review by cwilkers — APPROVED** [review]
In another set of PRs, I may need to nominate myself to be switched to an emeritus approver, but considering how emeritus status works in other venues, it would seem weird to self-nominate.

/lgtm

**Review by phoracek — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
