### PR TITLE
fixes #463

### LINKED ISSUE #463: NetworkPolicy PodSelector needs array instead of empty
Related to this issue: https://github.com/kubernetes/website/issues/6100

On this page: https://kubevirt.io/user-guide/virtual_machines/networkpolicy/

The PodSelector can't be empty or it gives an error message. The empty values needs to be replaced with empty array.

### PR DESCRIPTION
**Pull request by Bergiu**

### CODE REVIEW

**Comment by ansijain** [comment]
Hi, thank you for your commit. Would you mind signing your commit?

**Comment by jean-edouard** [comment]
@Bergiu thanks for fixing this. Could you please amend your commit with a sign off (`git commit -s`) so we can merge this?

**Comment by Bergiu** [comment]
no idea how to sign this afterwards. i have opened a new pull request for this:
https://github.com/kubevirt/user-guide/pull/472

**Pull request closed without merging**
