### PR TITLE
apparmor: Recommend removing libvirt package

### PR DESCRIPTION
**Pull request by andreabolognani**
Making local modifications to the AppArmor profile works, but (where possible) uninstalling the libvirt package also does the trick and is a much simpler workaround, so recommend that.

### CODE REVIEW

**Comment by andreabolognani** [comment]
@vasiliy-ul please take a look :)

**Review by vasiliy-ul — APPROVED** [review]

**Comment by andreabolognani** [comment]
Can anyone please approve the PR, and maybe explain why all the CI jobs have failed? I'm just tweaking a couple of paragraphs, so I would hardly expect that to ruffle automation's feathers.

**Comment by maiqueb** [comment]
/retest

... blindly assuming CI took a tumble.

**Comment by rmohr** [comment]
> /retest
> 
> ... blindly assuming CI took a tumble.

Not sure if retest works, given that these jobs are not run inside a prow job, or triggered via a prowjob. @andreabolognani would you mind running `git commit --amend` and resubmitting to trigger these jobs again?

**Comment by andreabolognani** [comment]
> would you mind running `git commit --amend` and resubmitting to trigger these jobs again?

@rmohr done. I think #624 might have fixed things in the meantime.

**Review by maiqueb — APPROVED** [review]
Thanks.

**Pull request merged**
