### PR TITLE
Access credential documentation

### PR DESCRIPTION
**Pull request by davidvossel**
This creates a new category on the side bar called "Accessing Virtual Machines" which contains the serial/console access documentation as well as the new ssh pub key injection via access credentials documentation.

### CODE REVIEW

**Comment by mazzystr** [comment]
@davidvossel I'm glad to see you working with mkdocs and awesome-pages easily

**Comment by davidvossel** [comment]
> @davidvossel I'm glad to see you working with mkdocs and awesome-pages easily

@mazzystr  yeah. It was really simple and easy to use. I especially found the preview functionality where the site is hosted locally helpful. I had the text editor in one window, and right as i hit save the preview site would immediately update. That surprised me the first time i saw it. It's great :+1:

**Comment by mazzystr** [comment]
re preview mode ... ain't that really neat??  We can do that with the Jekyll website too. 

I'm so glad to hear the content producing exp is a good one.

**Pull request merged**
