### PR TITLE
Document watchdog usage

### PR DESCRIPTION
**Pull request by rmohr**
Document the basic usage of watchdogs in kubevirt.

### CODE REVIEW

**Comment by fabiand** [comment]
@mazzystr do you know why the test are failing?

**Comment by rmohr** [comment]
> @mazzystr do you know why the test are failing?

I see 

```
Error: Invalid value for '-f' / '--config-file': Could not open file: mkdocs.yml: No such file or directory
```

@mazzystr maybe that tells you something

**Comment by codificat** [comment]
There are known issues and WIP to fix them for the CI around the user-guide, as part of the migration to a new site renderer engine (mkdocs).

@mazzystr can provide more details, but one thing that I believe should happen here is that the PR should be against the `source` branch instead of `master`.

@rmohr can you point this PR against `source`?

**Comment by rmohr** [comment]
> @mazzystr can provide more details, but one thing that I believe should happen here is that the PR should be against the `source` branch instead of `master`.

If it is due to a switch from `master` to e.g. `main` then I would prefer `main` which seems to be the bigger consensus. If that is not the reason, I am not sure I like this single  exception in the whole org.

**Comment by codificat** [comment]
> > @mazzystr can provide more details, but one thing that I believe should happen here is that the PR should be against the `source` branch instead of `master`.
> 
> If it is due to a switch from `master` to e.g. `main` then I would prefer `main` which seems to be the bigger consensus. If that is not the reason, I am not sure I like this single exception in the whole org.

The plan is to use `source` here in the same way we use it in the website (`kubevirt/kubevirt.github.io` repo). Both repos (user-guide and website) are served through github pages.

In other words: the switch to `source` makes this consistent with the other repo in the org that publishes a static website... makes sense?

OTOH the plan was to render the static site to a new `gh-pages` branch instead of `master` (the website uses `master`). AFAIK this is the default target branch on sites that use `mkdocs`. Obviously, no other repo in the org would be using `mkdocs`... should we use `master` or `main` for the target rendered documentation pages?  TBH it would still be a different type of `master` branch anyway: the default branch in this repo would switch to `source` the same way as in the website repo.

**Comment by mazzystr** [comment]
Please hold off on lgtm and approve on this pull request.  We are going through the final steps of migrating user-guide to the mkdocs markdown engine.   Many updates to CI are being made as we can see here with all the failed checks.  We don't want to have to unwork all that work.

Thanks!

**Comment by mazzystr** [comment]
We had a discussion re the pending content pull_reqs.  Repo owner will manually merge to avoid rework on the CI system.  I will rebase the pull/372.  

Hold label is removed @codificat

**Pull request merged**
