### PR TITLE
Update IPv6 addresses

### PR DESCRIPTION
**Pull request by ormergi**
Align with the new IPv6 default CIDR represented at https://github.com/kubevirt/kubevirt/pull/3328

Signed-off-by: Or Mergi <ormergi@redhat.com>

### CODE REVIEW

**Comment by maiqueb** [comment]
> Please add `documentation: ` in the subject.

Hm, @EdDev , this is a PR to the user guide. It *has* to be about documentation - I think it would be redundant.

**Comment by EdDev** [comment]
> > Please add `documentation: ` in the subject.
> 
> Hm, @EdDev , this is a PR to the user guide. It _has_ to be about documentation - I think it would be redundant.

Opsss... I though it is under kubevirt/kubevirt
Sorry!!

**Pull request merged**
